spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/effective_moblie
    username: ${DatabaseLogin}
    password: ${DatabasePass}
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 250


security:
  jwt:
    secret-key: ${JWT_secret_key}
    expiration: 86400000
    refresh-token:
      expiration: 86400000